### ISSUE TITLE
Install failure using luarocks on OS X

### ISSUE THREAD

**Issue by telemachus** [craigbarnes/lua-discount#5]
OS X: 10.11.6
lua: Lua 5.3.3  Copyright (C) 1994-2016 Lua.org, PUC-Rio
luarocks: luarocks 2.3.0

I can build and install using `make`, but if I try to install via luarocks, I get this failure:

    xmlpage.c:10:10: error: 'markdown.h' file not found with <angled> include; use
          "quotes" instead
    #include <markdown.h>
             ^~~~~~~~~~~~
             "markdown.h"
    1 error generated.
    make[1]: *** [xmlpage.o] Error 1
    make: *** [build/discount-2.2.1/libmarkdown.a] Error 2
    
    Error: Build error: Failed building.

It's not clear to me that this is an error with lua-discount (as opposed to discount or how homebrew installs discount as a library), but I'm starting here, since lua-discount changed most recently). The full build output is here, if that helps: https://gist.github.com/telemachus/43a9494986c6963e1b4d4a3ad9c7d8b3. Please let me know if I can give you any other helpful information.

**Comment by craigbarnes** [comment]
The rock no longer uses your system library -- it passes the `USE_LOCAL_DISCOUNT=1` option to trigger downloading/building/static linking a specific Discount release. In this case, LuaRocks is setting the `CC` variable, which breaks the (very fragile) Discount build system if it's somehow exported through.

I thought setting `MAKEOVERRIDES=` would stop the Discount build from inheriting the variables that LuaRocks sets, but I suspect this only works in newer versions of GNU make (OSX is stuck on an ancient version, because newer versions are GPLv3).

I'll push a possible fix shortly and then another release if you can confirm it's working.

**Comment by craigbarnes** [comment]
Hopefully commit 4b9aa38 should fix this. Could you try testing the SCM rock with

    luarocks --server=http://luarocks.org/dev --tree=/tmp/lua-discount-test-build install discount

**Comment by telemachus** [comment]
> Let me know if it builds ok now or if there are any other issues.

All clear. Thanks for the quick update and fix.

    discount 0.2.1-1 is now built and installed in /usr/local (license: ISC)
